<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ModularMonolith.Modules.Brand.QueryApplication</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Contracts\ModularMonolith.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Framework\ModularMonolith.Framework.csproj" />
    <ProjectReference Include="..\Adapter\Outbound\ModularMonolith.Modules.Brand.Adapter.Outbound.csproj" />
  </ItemGroup>
</Project>
