<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ModularMonolith.Modules.Admin.Adapter.Inbound.GraphQL</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" />
    <PackageReference Include="HotChocolate.AspNetCore.Authorization" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\BuildingBlocks\Framework\ModularMonolith.Framework.csproj" />
    <ProjectReference Include="..\..\..\Application\ModularMonolith.Modules.Admin.Application.csproj" />
  </ItemGroup>
</Project>
