<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\Framework\ModularMonolith.Framework.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\Application\ModularMonolith.Modules.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Orders\Application\ModularMonolith.Modules.Orders.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Customer\Application\ModularMonolith.Modules.Customer.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Payment\Application\ModularMonolith.Modules.Payment.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Supplier\Application\ModularMonolith.Modules.Supplier.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Brand\Application\ModularMonolith.Modules.Brand.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Admin\Application\ModularMonolith.Modules.Admin.Application.csproj" />
  </ItemGroup>
</Project>
